import { PrismaClient, Event as PrismaEvent } from "@prisma/client";
import { Event } from "@/lib/domain/event";
import { EventType } from "@/lib/domain/eventSchema";
import { MoneyUnit, Member } from "@/lib/domain/eventSchema";

export interface IEventRepository {
  createEvent: (eventData: Event) => Promise<EventType>;
  getEvent: (eventId: string) => Promise<EventType | null>;
  updateEvent: (id: string, eventData: Event) => Promise<EventType>;
}

export class EventRepository implements IEventRepository {
  constructor(private prisma: PrismaClient) {}

  async createEvent(eventData: Event): Promise<EventType> {
    // eventId is automatically generated by Prisma.
    // So, we don't need to pass it to the Prisma.
    const prismaEvent = await this.prisma.event.create({
      data: {
        eventName: eventData.eventName,
        memo: eventData.memo,
        fromDate: eventData.fromDate,
        toDate: eventData.toDate,
        moneyUnit: eventData.moneyUnit,
        members: {
          create: eventData.members,
        },
      },
      include: { members: true },
    });

    return this.toDomain(prismaEvent);
  }

  async getEvent(eventId: string): Promise<EventType | null> {
    const prismaEvent = await this.prisma.event.findUnique({
      where: { eventId },
      include: { members: true },
    });

    if (!prismaEvent) return null;
    return this.toDomain(prismaEvent);
  }

  async updateEvent(eventId: string, eventData: Event): Promise<EventType> {
    const prismaEvents = await this.prisma.event.update({
      where: { eventId },
      data: {
        ...eventData,
        members: { create: eventData.members },
      },
      include: { members: true },
    });

    return this.toDomain(prismaEvents);
  }

  // Prisma の Event を Domain の Event に変換するためのメソッド
  toDomain(prismaEvent: PrismaEvent & { members: Member[] }): EventType {
    return new Event({
      eventId: prismaEvent.eventId,
      eventName: prismaEvent.eventName,
      memo: prismaEvent.memo,
      fromDate: prismaEvent.fromDate.toISOString(),
      toDate: prismaEvent.toDate.toISOString(),
      members: prismaEvent.members,
      moneyUnit: prismaEvent.moneyUnit as MoneyUnit,
    });
  }
}
